version: '3'

services:
  app:
    image: go4ble/hermes-logger:latest
    build: .

  mqtt_subscription:
    image: go4ble/hermes-logger:latest
    build: .
    command: bundle exec rails runner lib/tasks/mqtt_subscription.rake

  # mongo:
